<?php
// Automatically Generated by TestLink Installer - Thu, 24 Oct 13 15:03:17 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'teste');
define('DB_PASS', 'T3st32013');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
